[program:vless_celery_main]
command=/usr/bin/celery -A celery_app:app worker --loglevel=info --concurrency=8 --queues=high_priority,stability_check --hostname=main_worker_%%h
directory=/root/vless-vpn-bot
user=root
numprocs=1
stdout_logfile=/var/log/celery/main.log
stderr_logfile=/var/log/celery/main.err
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30

[program:vless_celery_secondary]
command=/usr/bin/celery -A celery_app:app worker --loglevel=info --concurrency=8 --queues=medium_priority,low_priority --hostname=secondary_worker_%%h
directory=/root/vless-vpn-bot
user=root
numprocs=1
stdout_logfile=/var/log/celery/secondary.log
stderr_logfile=/var/log/celery/secondary.err
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30

[program:vless_celery_beat]
command=/usr/bin/celery -A celery_app:app beat --loglevel=info
directory=/root/vless-vpn-bot
user=root
numprocs=1
stdout_logfile=/var/log/celery/beat.log
stderr_logfile=/var/log/celery/beat.err
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30

[program:vless_celery_monitor]
command=/usr/bin/celery -A celery_app:app flower --port=5555
directory=/root/vless-vpn-bot
user=root
numprocs=1
stdout_logfile=/var/log/celery/flower.log
stderr_logfile=/var/log/celery/flower.err
autostart=false
autorestart=true
startsecs=10
stopwaitsecs=30
